"use client";

import { useEffect, useMemo, useState } from "react";
import {
  AlertTriangle,
  Building2,
  CheckCircle2,
  Cloud,
  CloudOff,
  Database,
  Download,
  FileCheck2,
  Image as ImageIcon,
  LockKeyhole,
  Save,
  Upload,
  ShieldCheck,
  Trash2,
} from "lucide-react";

type SensitivityLevel = "low" | "medium" | "high" | "critical";

type ComplianceSettings = {
  organisationName: string;
  country: string;
  contactPerson: string;
  contactEmail: string;
  website: string;
  defaultCurrency: string;
  defaultGeography: string;
  reportFooter: string;
  projectPurpose: string;
  lawfulBasis: string;
  sensitivityLevel: SensitivityLevel;
  containsPersonalData: boolean;
  containsHealthData: boolean;
  containsChildrenData: boolean;
  containsFinancialData: boolean;
  containsPreciseLocation: boolean;
  piiScanRequired: boolean;
  reviewerApprovalRequired: boolean;
  exportLoggingEnabled: boolean;
  retentionPeriod: string;
  deletionInstruction: string;
};

type ActiveProject = {
  id?: string;
  backendId?: number;
  organisation?: string;
  country?: string;
  sensitivity?: string;
  name?: string;
};

type DatabaseStatus = {
  ok?: boolean;
  status?: string;
  database_engine?: string;
  table_count?: number;
  production_note?: string;
  detail?: string;
};

type ApiComplianceSetting = {
  id: number;
  project_id?: number | null;
  organisation_name: string;
  country: string;
  contact_person?: string | null;
  contact_email?: string | null;
  project_purpose?: string | null;
  lawful_basis?: string | null;
  sensitivity_level: SensitivityLevel;
  contains_personal_data: number;
  contains_health_data: number;
  contains_children_data: number;
  contains_financial_data: number;
  contains_precise_location: number;
  pii_scan_required: number;
  reviewer_approval_required: number;
  export_logging_enabled: number;
  retention_period?: string | null;
  deletion_instruction?: string | null;
  compliance_score: number;
  created_at: string;
};

const STORAGE_KEY = "daliliComplianceSettings";
const ACTIVE_PROJECT_KEY = "dalili.activeProject";
const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL || process.env.NEXT_PUBLIC_API_BASE || "http://127.0.0.1:8000";
const ORG_LOGO_KEY = "dalili.organisationLogo";

const defaultSettings: ComplianceSettings = {
  organisationName: "",
  country: "Uganda",
  contactPerson: "Dalili user",
  contactEmail: "",
  website: "",
  defaultCurrency: "UGX",
  defaultGeography: "Uganda",
  reportFooter: "Generated by Dalili. Validate findings before external sharing.",
  projectPurpose: "Monitoring, evaluation, learning and donor reporting",
  lawfulBasis: "Consent / programme monitoring purpose documented by the organisation",
  sensitivityLevel: "medium",
  containsPersonalData: true,
  containsHealthData: false,
  containsChildrenData: false,
  containsFinancialData: false,
  containsPreciseLocation: false,
  piiScanRequired: true,
  reviewerApprovalRequired: true,
  exportLoggingEnabled: true,
  retentionPeriod: "24 months after project closure",
  deletionInstruction:
    "Delete source files and derived outputs after the approved retention period unless the organisation renews the project record.",
};

function readJson<T>(key: string): T | null {
  if (typeof window === "undefined") return null;
  try {
    const saved = window.localStorage.getItem(key);
    return saved ? (JSON.parse(saved) as T) : null;
  } catch {
    return null;
  }
}

function loadSettings(): ComplianceSettings {
  return { ...defaultSettings, ...(readJson<Partial<ComplianceSettings>>(STORAGE_KEY) ?? {}) };
}

function toApiPayload(settings: ComplianceSettings, score: number, activeProject: ActiveProject | null) {
  return {
    project_id: activeProject?.backendId ?? null,
    organisation_name: settings.organisationName,
    country: settings.country,
    contact_person: settings.contactPerson,
    contact_email: settings.contactEmail,
    project_purpose: settings.projectPurpose,
    lawful_basis: settings.lawfulBasis,
    sensitivity_level: settings.sensitivityLevel,
    contains_personal_data: settings.containsPersonalData ? 1 : 0,
    contains_health_data: settings.containsHealthData ? 1 : 0,
    contains_children_data: settings.containsChildrenData ? 1 : 0,
    contains_financial_data: settings.containsFinancialData ? 1 : 0,
    contains_precise_location: settings.containsPreciseLocation ? 1 : 0,
    pii_scan_required: settings.piiScanRequired ? 1 : 0,
    reviewer_approval_required: settings.reviewerApprovalRequired ? 1 : 0,
    export_logging_enabled: settings.exportLoggingEnabled ? 1 : 0,
    retention_period: settings.retentionPeriod,
    deletion_instruction: settings.deletionInstruction,
    compliance_score: score,
  };
}

function fromApiPayload(record: ApiComplianceSetting): ComplianceSettings {
  return {
    organisationName: record.organisation_name || defaultSettings.organisationName,
    country: record.country || defaultSettings.country,
    contactPerson: record.contact_person || defaultSettings.contactPerson,
    contactEmail: record.contact_email || defaultSettings.contactEmail,
    website: defaultSettings.website,
    defaultCurrency: defaultSettings.defaultCurrency,
    defaultGeography: defaultSettings.defaultGeography,
    reportFooter: defaultSettings.reportFooter,
    projectPurpose: record.project_purpose || defaultSettings.projectPurpose,
    lawfulBasis: record.lawful_basis || defaultSettings.lawfulBasis,
    sensitivityLevel: record.sensitivity_level || defaultSettings.sensitivityLevel,
    containsPersonalData: Boolean(record.contains_personal_data),
    containsHealthData: Boolean(record.contains_health_data),
    containsChildrenData: Boolean(record.contains_children_data),
    containsFinancialData: Boolean(record.contains_financial_data),
    containsPreciseLocation: Boolean(record.contains_precise_location),
    piiScanRequired: Boolean(record.pii_scan_required),
    reviewerApprovalRequired: Boolean(record.reviewer_approval_required),
    exportLoggingEnabled: Boolean(record.export_logging_enabled),
    retentionPeriod: record.retention_period || defaultSettings.retentionPeriod,
    deletionInstruction: record.deletion_instruction || defaultSettings.deletionInstruction,
  };
}

async function backendHealth() {
  const response = await fetch(`${API_BASE}/health`);
  if (!response.ok) throw new Error("Backend not available");
  return response.json();
}

async function databaseStatus() {
  const response = await fetch(`${API_BASE}/ops/database`);
  if (!response.ok) throw new Error("Database status endpoint not available");
  return response.json() as Promise<DatabaseStatus>;
}

function statusBadge(level: SensitivityLevel) {
  if (level === "critical") return { label: "Critical sensitivity", className: "bg-red-50 text-red-700 border border-red-200" };
  if (level === "high") return { label: "High sensitivity", className: "bg-orange-50 text-orange-700 border border-orange-200" };
  if (level === "medium") return { label: "Medium sensitivity", className: "bg-amber-50 text-amber-700 border border-amber-200" };
  return { label: "Low sensitivity", className: "bg-emerald-50 text-emerald-700 border border-emerald-200" };
}

function BooleanRow({
  title,
  description,
  checked,
  onChange,
}: {
  title: string;
  description: string;
  checked: boolean;
  onChange: (value: boolean) => void;
}) {
  return (
    <label className="flex cursor-pointer items-start justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-4 transition hover:border-emerald-200 hover:bg-emerald-50/30">
      <span>
        <span className="block text-sm font-semibold text-[#102033]">{title}</span>
        <span className="mt-1 block text-xs leading-5 text-slate-500">{description}</span>
      </span>
      <input
        type="checkbox"
        checked={checked}
        onChange={(event) => onChange(event.target.checked)}
        className="mt-1 h-5 w-5 rounded border-slate-300 accent-[#073B2A]"
      />
    </label>
  );
}

export function SettingsClient() {
  const [settings, setSettings] = useState<ComplianceSettings>(defaultSettings);
  const [activeProject, setActiveProject] = useState<ActiveProject | null>(null);
  const [savedAt, setSavedAt] = useState<string>("");
  const [backendOnline, setBackendOnline] = useState(false);
  const [backendMessage, setBackendMessage] = useState("Checking backend...");
  const [databaseMessage, setDatabaseMessage] = useState("Database status not checked yet.");
  const [organisationLogo, setOrganisationLogo] = useState<string | null>(null);

  useEffect(() => {
    const localSettings = loadSettings();
    const project = readJson<ActiveProject>(ACTIVE_PROJECT_KEY);
    setSettings({
      ...localSettings,
      organisationName: project?.organisation || localSettings.organisationName,
      country: project?.country || localSettings.country,
    });
    setActiveProject(project);
    setOrganisationLogo(window.localStorage.getItem(ORG_LOGO_KEY));
    checkBackend();
  }, []);

  const checks = useMemo(() => {
    const items = [
      { label: "Processing purpose recorded", passed: settings.projectPurpose.trim().length > 10 },
      { label: "Lawful basis documented", passed: settings.lawfulBasis.trim().length > 10 },
      { label: "PII scan required before analysis", passed: settings.piiScanRequired },
      { label: "Reviewer approval required for exports", passed: settings.reviewerApprovalRequired },
      { label: "Export logging enabled", passed: settings.exportLoggingEnabled },
      { label: "Retention period defined", passed: settings.retentionPeriod.trim().length > 3 },
    ];
    const score = Math.round((items.filter((item) => item.passed).length / items.length) * 100);
    return { items, score };
  }, [settings]);

  const sensitivity = statusBadge(settings.sensitivityLevel);

  function update<K extends keyof ComplianceSettings>(key: K, value: ComplianceSettings[K]) {
    setSettings((current) => ({ ...current, [key]: value }));
  }

  function handleLogoUpload(file: File | null) {
    if (!file) return;
    if (!file.type.startsWith("image/")) {
      setBackendMessage("Please upload an image file for the organisation logo.");
      return;
    }
    const reader = new FileReader();
    reader.onload = () => {
      const dataUrl = String(reader.result || "");
      setOrganisationLogo(dataUrl);
      window.localStorage.setItem(ORG_LOGO_KEY, dataUrl);
      window.dispatchEvent(new Event("dalili-branding-changed"));
      setBackendMessage("Organisation logo saved locally and will appear in the app and local report/project exports.");
    };
    reader.readAsDataURL(file);
  }

  function removeLogo() {
    setOrganisationLogo(null);
    window.localStorage.removeItem(ORG_LOGO_KEY);
    window.dispatchEvent(new Event("dalili-branding-changed"));
    setBackendMessage("Organisation logo removed from local branding.");
  }

  async function checkBackend() {
    try {
      await backendHealth();
      setBackendOnline(true);
      setBackendMessage("Backend connected. Compliance settings can be stored in the database.");
      try {
        const db = await databaseStatus();
        setDatabaseMessage(`${db.status || (db.ok ? "connected" : "error")} · ${db.database_engine || "unknown database"} · ${db.table_count ?? 0} tables`);
      } catch {
        setDatabaseMessage("Backend is online, but /ops/database is not available. Check the v50/v51 operations router.");
      }
    } catch {
      setBackendOnline(false);
      setBackendMessage("Backend offline. Settings will be saved only in browser storage until FastAPI is running.");
      setDatabaseMessage("Database status unavailable because backend is offline.");
    }
  }

  function saveSettings() {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(settings));
    const now = new Date().toLocaleString();
    setSavedAt(now);
    window.localStorage.setItem(
      "daliliAuditSettingsSnapshot",
      JSON.stringify({ ...settings, savedAt: now, complianceScore: checks.score, activeProject }),
    );
    setBackendMessage("Settings saved in browser storage. Use 'Save to backend' to store them in the database.");
  }

  async function saveToBackend() {
    saveSettings();
    try {
      await backendHealth();
      const response = await fetch(`${API_BASE}/compliance-settings`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(toApiPayload(settings, checks.score, activeProject)),
      });
      if (!response.ok) {
        const text = await response.text();
        throw new Error(text || "Backend save failed");
      }
      const record = (await response.json()) as ApiComplianceSetting;
      setBackendOnline(true);
      setBackendMessage(`Compliance settings saved to backend as record #${record.id}.`);
      setSavedAt(new Date(record.created_at).toLocaleString());
    } catch (error) {
      setBackendOnline(false);
      setBackendMessage(error instanceof Error ? error.message : "Could not save compliance settings to backend.");
    }
  }

  async function loadLatestFromBackend() {
    try {
      await backendHealth();
      const suffix = activeProject?.backendId ? `?project_id=${activeProject.backendId}` : "";
      const response = await fetch(`${API_BASE}/compliance-settings/latest${suffix}`);
      if (!response.ok) throw new Error("No backend compliance settings found for this project yet.");
      const record = (await response.json()) as ApiComplianceSetting;
      const loaded = fromApiPayload(record);
      setSettings(loaded);
      window.localStorage.setItem(STORAGE_KEY, JSON.stringify(loaded));
      setBackendOnline(true);
      setBackendMessage(`Loaded backend compliance record #${record.id}.`);
      setSavedAt(new Date(record.created_at).toLocaleString());
    } catch (error) {
      setBackendMessage(error instanceof Error ? error.message : "Could not load backend compliance settings.");
    }
  }

  function resetSettings() {
    setSettings(defaultSettings);
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(defaultSettings));
    setSavedAt(new Date().toLocaleString());
  }

  function exportComplianceMemo() {
    const sensitiveCategories = [
      settings.containsPersonalData ? "Personal data" : null,
      settings.containsHealthData ? "Health/HIV/SRH data" : null,
      settings.containsChildrenData ? "Children/adolescent data" : null,
      settings.containsFinancialData ? "Financial/vulnerability data" : null,
      settings.containsPreciseLocation ? "Precise location data" : null,
    ].filter(Boolean);

    const text = [
      "DALILI COMPLIANCE AND GOVERNANCE MEMO",
      "====================================",
      `Project: ${activeProject?.name || "No active project selected"}`,
      `Backend project ID: ${activeProject?.backendId ?? "Not linked"}`,
      `Organisation: ${settings.organisationName}`,
      `Country: ${settings.country}`,
      `Contact person: ${settings.contactPerson}`,
      `Contact email: ${settings.contactEmail}`,
      `Website: ${settings.website || "Not specified"}`,
      `Default currency: ${settings.defaultCurrency}`,
      `Default geography: ${settings.defaultGeography}`,
      "",
      "PROCESSING PURPOSE",
      settings.projectPurpose,
      "",
      "LAWFUL BASIS / JUSTIFICATION",
      settings.lawfulBasis,
      "",
      `Sensitivity level: ${settings.sensitivityLevel}`,
      `Sensitive categories: ${sensitiveCategories.length ? sensitiveCategories.join(", ") : "None selected"}`,
      "",
      "GOVERNANCE CONTROLS",
      `PII scan required: ${settings.piiScanRequired ? "Yes" : "No"}`,
      `Reviewer approval required: ${settings.reviewerApprovalRequired ? "Yes" : "No"}`,
      `Export logging enabled: ${settings.exportLoggingEnabled ? "Yes" : "No"}`,
      `Retention period: ${settings.retentionPeriod}`,
      `Deletion instruction: ${settings.deletionInstruction}`,
      "",
      "CHECKLIST",
      ...checks.items.map((item) => `${item.passed ? "PASS" : "REVIEW"}: ${item.label}`),
      "",
      `Compliance readiness score: ${checks.score}%`,
      `Generated: ${new Date().toLocaleString()}`,
    ].join("\n");

    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "dalili-compliance-governance-memo.txt";
    link.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="space-y-6">
      <div className="grid gap-4 lg:grid-cols-[1.7fr_1fr]">
        <div className="card p-6">
          <div className="flex flex-wrap items-start justify-between gap-4">
            <div>
              <div className="flex items-center gap-2 text-sm font-semibold uppercase tracking-wide text-emerald-700">
                <ShieldCheck className="h-4 w-4" /> Settings & Compliance
              </div>
              <h1 className="mt-3 text-2xl font-bold text-[#102033]">Governance setup for safe analysis</h1>
              <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">
                Configure how Dalili should treat project data before analysis, reporting and exports. This module now stores governance settings in the backend when FastAPI is running.
              </p>
            </div>
            <span className={`badge ${sensitivity.className}`}>{sensitivity.label}</span>
          </div>
        </div>

        <div className="card p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-semibold text-slate-500">Readiness score</p>
              <p className="mt-1 text-4xl font-black text-[#073B2A]">{checks.score}%</p>
            </div>
            <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-700">
              <FileCheck2 className="h-7 w-7" />
            </div>
          </div>
          <div className="mt-4 h-3 rounded-full bg-slate-100">
            <div className="h-3 rounded-full bg-[#073B2A] transition-all" style={{ width: `${checks.score}%` }} />
          </div>
          {savedAt ? <p className="mt-3 text-xs text-slate-500">Last saved: {savedAt}</p> : null}
        </div>
      </div>

      <div className="card p-5">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div className="flex items-start gap-3">
            <div className={`mt-1 rounded-xl p-2 ${backendOnline ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>
              {backendOnline ? <Cloud className="h-5 w-5" /> : <CloudOff className="h-5 w-5" />}
            </div>
            <div>
              <h2 className="text-sm font-bold text-[#102033]">Backend compliance storage</h2>
              <p className="mt-1 text-sm text-slate-600">{backendMessage}</p>
              <p className="mt-1 text-xs font-semibold text-slate-500">Database: {databaseMessage}</p>
              <p className="mt-1 text-xs text-slate-500">
                Active project: {activeProject?.name || "None selected"} | Backend ID: {activeProject?.backendId ?? "Not linked"}
              </p>
            </div>
          </div>
          <div className="flex flex-wrap gap-2">
            <button onClick={checkBackend} className="rounded-2xl border border-slate-300 bg-white px-4 py-2 text-sm font-bold text-[#102033] hover:bg-slate-50">
              Check backend
            </button>
            <button onClick={loadLatestFromBackend} className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-2 text-sm font-bold text-emerald-800 hover:bg-emerald-100">
              Load latest
            </button>
            <button onClick={saveToBackend} className="rounded-2xl bg-[#073B2A] px-4 py-2 text-sm font-bold text-white hover:bg-[#0b5e3c]">
              Save to backend
            </button>
          </div>
        </div>
      </div>

      <div className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]">
        <div className="space-y-6">
          <div className="card p-6">
            <div className="mb-5 flex items-center gap-2">
              <Building2 className="h-5 w-5 text-[#073B2A]" />
              <h2 className="text-lg font-bold text-[#102033]">Organisation profile</h2>
            </div>
            <div className="mb-5 rounded-2xl border border-slate-200 bg-slate-50 p-4">
              <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                <div className="flex items-center gap-4">
                  <div className="flex h-20 w-20 items-center justify-center rounded-2xl border border-slate-200 bg-white p-2">
                    {organisationLogo ? <img src={organisationLogo} alt="Organisation logo" className="max-h-full max-w-full object-contain" /> : <ImageIcon className="h-8 w-8 text-slate-400" />}
                  </div>
                  <div>
                    <p className="text-sm font-bold text-[#102033]">Organisation logo</p>
                    <p className="mt-1 text-xs leading-5 text-slate-500">Used in the topbar, project briefs and local report exports. Backend logo storage can be added during deployment hardening.</p>
                  </div>
                </div>
                <div className="flex flex-wrap gap-2">
                  <label className="inline-flex cursor-pointer items-center gap-2 rounded-2xl bg-[#073B2A] px-4 py-2 text-sm font-bold text-white hover:bg-[#0b5e3c]">
                    <Upload className="h-4 w-4" /> Upload logo
                    <input type="file" accept="image/*" onChange={(event) => handleLogoUpload(event.target.files?.[0] ?? null)} className="hidden" />
                  </label>
                  {organisationLogo ? <button onClick={removeLogo} className="rounded-2xl border border-red-200 bg-red-50 px-4 py-2 text-sm font-bold text-red-700 hover:bg-red-100">Remove</button> : null}
                </div>
              </div>
            </div>
            <div className="grid gap-4 md:grid-cols-2">
              <label className="text-sm font-semibold text-slate-700">
                Organisation name
                <input value={settings.organisationName} onChange={(event) => update("organisationName", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-[#073B2A]" />
              </label>
              <label className="text-sm font-semibold text-slate-700">
                Country
                <input value={settings.country} onChange={(event) => update("country", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-[#073B2A]" />
              </label>
              <label className="text-sm font-semibold text-slate-700">
                Contact person
                <input value={settings.contactPerson} onChange={(event) => update("contactPerson", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-[#073B2A]" />
              </label>
              <label className="text-sm font-semibold text-slate-700">
                Contact email
                <input value={settings.contactEmail} onChange={(event) => update("contactEmail", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-[#073B2A]" />
              </label>
              <label className="text-sm font-semibold text-slate-700">
                Website
                <input value={settings.website} onChange={(event) => update("website", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-[#073B2A]" placeholder="https://example.org" />
              </label>
              <label className="text-sm font-semibold text-slate-700">
                Default currency
                <input value={settings.defaultCurrency} onChange={(event) => update("defaultCurrency", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-[#073B2A]" placeholder="UGX" />
              </label>
              <label className="text-sm font-semibold text-slate-700">
                Default reporting geography
                <input value={settings.defaultGeography} onChange={(event) => update("defaultGeography", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-[#073B2A]" placeholder="Uganda / Wakiso / Kampala" />
              </label>
              <label className="text-sm font-semibold text-slate-700 md:col-span-2">
                Default report footer
                <input value={settings.reportFooter} onChange={(event) => update("reportFooter", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-[#073B2A]" />
              </label>
            </div>
          </div>

          <div className="card p-6">
            <div className="mb-5 flex items-center gap-2">
              <Database className="h-5 w-5 text-[#073B2A]" />
              <h2 className="text-lg font-bold text-[#102033]">Processing purpose</h2>
            </div>
            <div className="grid gap-4">
              <label className="text-sm font-semibold text-slate-700">
                Purpose of analysis
                <textarea value={settings.projectPurpose} onChange={(event) => update("projectPurpose", event.target.value)} rows={3} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-[#073B2A]" />
              </label>
              <label className="text-sm font-semibold text-slate-700">
                Lawful basis / justification
                <textarea value={settings.lawfulBasis} onChange={(event) => update("lawfulBasis", event.target.value)} rows={3} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-[#073B2A]" />
              </label>
              <label className="text-sm font-semibold text-slate-700">
                Data sensitivity level
                <select value={settings.sensitivityLevel} onChange={(event) => update("sensitivityLevel", event.target.value as SensitivityLevel)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-[#073B2A]">
                  <option value="low">Low - aggregate or non-sensitive operational data</option>
                  <option value="medium">Medium - programme records with limited personal data</option>
                  <option value="high">High - health, financial, child/adolescent or precise location data</option>
                  <option value="critical">Critical - protection, SGBV, HIV case-level or highly identifiable data</option>
                </select>
              </label>
            </div>
          </div>

          <div className="card p-6">
            <div className="mb-5 flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-[#f59e0b]" />
              <h2 className="text-lg font-bold text-[#102033]">Sensitive data flags</h2>
            </div>
            <div className="grid gap-3 md:grid-cols-2">
              <BooleanRow title="Personal data" description="Names, phone numbers, IDs, emails or other identifiable records." checked={settings.containsPersonalData} onChange={(value) => update("containsPersonalData", value)} />
              <BooleanRow title="Health, HIV, SRH or mental health data" description="Service records or responses that require stricter handling." checked={settings.containsHealthData} onChange={(value) => update("containsHealthData", value)} />
              <BooleanRow title="Children or adolescent data" description="Records involving minors or young people needing extra protection." checked={settings.containsChildrenData} onChange={(value) => update("containsChildrenData", value)} />
              <BooleanRow title="Financial or vulnerability data" description="Poverty, income, cash transfer, debt or vulnerability indicators." checked={settings.containsFinancialData} onChange={(value) => update("containsFinancialData", value)} />
              <BooleanRow title="Precise location data" description="Household GPS or locations that can identify people or communities." checked={settings.containsPreciseLocation} onChange={(value) => update("containsPreciseLocation", value)} />
            </div>
          </div>
        </div>

        <div className="space-y-6">
          <div className="card p-6">
            <div className="mb-5 flex items-center gap-2">
              <LockKeyhole className="h-5 w-5 text-[#073B2A]" />
              <h2 className="text-lg font-bold text-[#102033]">Controls</h2>
            </div>
            <div className="space-y-3">
              <BooleanRow title="Require PII scan" description="Users must review personal identifiers before analysis." checked={settings.piiScanRequired} onChange={(value) => update("piiScanRequired", value)} />
              <BooleanRow title="Require reviewer approval" description="Reports and sensitive exports require human approval." checked={settings.reviewerApprovalRequired} onChange={(value) => update("reviewerApprovalRequired", value)} />
              <BooleanRow title="Enable export logging" description="Record who exported what, and when, for audit purposes." checked={settings.exportLoggingEnabled} onChange={(value) => update("exportLoggingEnabled", value)} />
            </div>
          </div>

          <div className="card p-6">
            <h2 className="text-lg font-bold text-[#102033]">Retention and deletion</h2>
            <label className="mt-4 block text-sm font-semibold text-slate-700">
              Retention period
              <input value={settings.retentionPeriod} onChange={(event) => update("retentionPeriod", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-[#073B2A]" />
            </label>
            <label className="mt-4 block text-sm font-semibold text-slate-700">
              Deletion instruction
              <textarea value={settings.deletionInstruction} onChange={(event) => update("deletionInstruction", event.target.value)} rows={4} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-[#073B2A]" />
            </label>
          </div>

          <div className="card p-6">
            <h2 className="text-lg font-bold text-[#102033]">Checklist</h2>
            <div className="mt-4 space-y-3">
              {checks.items.map((item) => (
                <div key={item.label} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-3">
                  {item.passed ? <CheckCircle2 className="h-5 w-5 text-emerald-600" /> : <AlertTriangle className="h-5 w-5 text-amber-600" />}
                  <span className="text-sm font-medium text-slate-700">{item.label}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-1">
            <button onClick={saveSettings} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[#073B2A] px-4 py-3 text-sm font-bold text-white transition hover:bg-[#0b5e3c]">
              <Save className="h-4 w-4" /> Save locally
            </button>
            <button onClick={saveToBackend} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-emerald-700 px-4 py-3 text-sm font-bold text-white transition hover:bg-emerald-800">
              <Cloud className="h-4 w-4" /> Save to backend
            </button>
            <button onClick={exportComplianceMemo} className="inline-flex items-center justify-center gap-2 rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm font-bold text-[#102033] transition hover:bg-slate-50">
              <Download className="h-4 w-4" /> Export memo
            </button>
            <button onClick={resetSettings} className="inline-flex items-center justify-center gap-2 rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-bold text-red-700 transition hover:bg-red-100">
              <Trash2 className="h-4 w-4" /> Reset
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
